Parameters:

  AcmCertificateArn:
    Type: String

Resources:

  BlogS3Bucket:   
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  BlogCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Enabled: true
        Aliases:
        - tvc.io
        Origins:
        - Id: blog-s3-bucket-cloudfront 
          DomainName: !Sub "${BlogS3Bucket}.s3-website-${AWS::Region}.${AWS::URLSuffix}"
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn # has to be in us-east-1
          SslSupportMethod: sni-only # vip is $600 / month!
        DefaultCacheBehavior:
          TargetOriginId: blog-s3-bucket-cloudfront
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:       
            QueryString: false  

  TvcIoZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: tvc.io.

  TvcIoRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref TvcIoZone
      RecordSets:
      - Name: tvc.io.
        Type: A
        AliasTarget:
          DNSName: !GetAtt BlogCloudfront.DomainName
          HostedZoneId: Z2FDTNDATAQYW2 # magic cloudfront string
      - Name: tvc.io.
        Type: MX 
        TTL: 3600
        ResourceRecords:
        - "1 aspmx.l.google.com"
        - "5 alt1.aspmx.l.google.com"
        - "5 alt2.aspmx.l.google.com"
        - "10 aspmx2.googlemail.com"
        - "10 aspmx3.googlemail.com"
      - Name: spoiler-free.tvc.io.
        Type: CNAME 
        TTL: 600
        ResourceRecords:
        - "spoiler-free.tvc.io.herokudns.com"
      - Name: tube.tvc.io.
        Type: CNAME 
        TTL: 600
        ResourceRecords:
        - "tube.tvc.io.herokudns.com"

  TravisUser: 
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyName: allow-s3
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - s3:get*
            - s3:list*
            - s3:put*
            Resource:
            - !GetAtt BlogS3Bucket.Arn
            - !Sub "${BlogS3Bucket.Arn}/*"

