Parameters:

  CloudfrontOriginAccessIdentity:
    Type: String

  CloudfrontCanonicalUserId:
    Type: String

Resources:

  BlogS3Bucket:   
    Type: AWS::S3::Bucket

  BlogS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BlogS3Bucket
      PolicyDocument:
        Statement:
        - Action: s3:GetObject       
          Effect: Allow
          Resource:
          - !Sub "${BlogS3Bucket.Arn}/*"
          Principal:
            CanonicalUser: !Ref CloudfrontCanonicalUserId

  BlogCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Enabled: true
        Aliases:
        - tvc.io
        Origins:
        - Id: blog-s3-bucket-cloudfront 
          DomainName: !GetAtt BlogS3Bucket.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudfrontOriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: blog-s3-bucket-cloudfront
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:       
            QueryString: false  

  TvcIoZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: tvc.io.

  TvcIoRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref TvcIoZone
      RecordSets:
      - Name: tvc.io.
        Type: A
        AliasTarget:
          DNSName: !GetAtt BlogCloudfront.DomainName
          HostedZoneId: Z2FDTNDATAQYW2 # magic cloudfront string
      - Name: tvc.io.
        Type: MX
        TTL: 3600
        ResourceRecords:
        - "1 aspmx.l.google.com"
        - "5 alt1.aspmx.l.google.com"
        - "5 alt2.aspmx.l.google.com"
        - "10 aspmx2.googlemail.com"
        - "10 aspmx3.googlemail.com"

  TravisUser: 
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyName: allow-s3
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - s3:get*
            - s3:list*
            - s3:put*
            Resource:
            - !GetAtt BlogS3Bucket.Arn
            - !Sub "${BlogS3Bucket.Arn}/*"

