name: Deploy website
on:
  push:
    branches:
      - $default-branch
      - miserable-yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the website
        run: |
          export HUGO_VERSION=0.91.2
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -zxf hugo* hugo
          chmod +x hugo
          ./hugo
      - name: Upload the website
        run: aws s3 sync --acl public-read ./public s3://${WEBSITE_BUCKET}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          WEBSITE_BUCKET: ${{ secrets.WEBSITE_BUCKET }}
          AWS_DEFAULT_REGION: 'eu-west-1'
      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
            --paths "/*" > /dev/null
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: 'eu-west-1'
        